# fly.toml app configuration file generated for sivukhin-wasm-test on 2025-08-14T00:59:38+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sivukhin-wasm-test'
primary_region = 'ams'

[build]

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  min_machines_running = 1

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
